
package javaapplication9;

import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class MainMenu extends javax.swing.JFrame {
    
    //Deklarasi variabel
    int Price_Croissant = 25000;
    int Price_Corompoloni = 28000;
    int Price_CheseeCake = 40000;
    int Price_CherryPie = 25000;
    int Price_Cookies = 23000;
    int Price_CoklatPanas = 28000;
    int Price_GreenTea = 28000;
    int Price_Coffee = 22000;
    int Price_Milkshake = 28000;
    int Price_MineralWater = 8000;
    
    int iTax, iTotal, iSubTotal, iPay;
    
    int[] itemcost = new int[10];//array
            
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jchkCroissant = new javax.swing.JCheckBox();
        jchkCorompoloni = new javax.swing.JCheckBox();
        jchkCheseeCake = new javax.swing.JCheckBox();
        jchkCherryPie = new javax.swing.JCheckBox();
        jchkCookies = new javax.swing.JCheckBox();
        jtxtCroissant = new javax.swing.JTextField();
        jtxtCorompoloni = new javax.swing.JTextField();
        jtxtCheseeCake = new javax.swing.JTextField();
        jtxtCherryPie = new javax.swing.JTextField();
        jtxtCookies = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jchkCoklatPanas = new javax.swing.JCheckBox();
        jchkGreenTea = new javax.swing.JCheckBox();
        jchkCoffee = new javax.swing.JCheckBox();
        jchkMilkshake = new javax.swing.JCheckBox();
        jchkMineralWater = new javax.swing.JCheckBox();
        jtxtCoklatPanas = new javax.swing.JTextField();
        jtxtGreenTea = new javax.swing.JTextField();
        jtxtCoffee = new javax.swing.JTextField();
        jtxtMilkshake = new javax.swing.JTextField();
        jtxtMineralWater = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcmbpaymethod = new javax.swing.JComboBox<>();
        jtxtPay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtChange = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbuttonTotal = new javax.swing.JButton();
        jbuttonReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtArea = new javax.swing.JTextArea();
        jbuttonOrder = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jbuttonExit = new javax.swing.JButton();
        jbuttonChange = new javax.swing.JButton();
        jbuttonCetakPesanan = new javax.swing.JButton();
        jbuttonNewOrder = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(205, 183, 158));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 78, 55), 4));
        jPanel1.setForeground(new java.awt.Color(111, 78, 55));

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        jLabel10.setText("Main Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel10)
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 933, -1));

        jPanel2.setBackground(new java.awt.Color(205, 183, 158));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(111, 78, 55)));
        jPanel2.setForeground(new java.awt.Color(111, 78, 55));

        jchkCroissant.setText("Croissant");
        jchkCroissant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkCroissantActionPerformed(evt);
            }
        });

        jchkCorompoloni.setText("Cromboloni");
        jchkCorompoloni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkCorompoloniActionPerformed(evt);
            }
        });

        jchkCheseeCake.setText("Cheese Cake");
        jchkCheseeCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkCheseeCakeActionPerformed(evt);
            }
        });

        jchkCherryPie.setText("Cherry Pie");
        jchkCherryPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkCherryPieActionPerformed(evt);
            }
        });

        jchkCookies.setText("Cookies");
        jchkCookies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkCookiesActionPerformed(evt);
            }
        });

        jtxtCroissant.setBackground(new java.awt.Color(197, 167, 135));
        jtxtCroissant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCroissant.setText("0");
        jtxtCroissant.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jtxtCroissant.setEnabled(false);
        jtxtCroissant.setMinimumSize(new java.awt.Dimension(72, 22));
        jtxtCroissant.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtCroissant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCroissantActionPerformed(evt);
            }
        });
        jtxtCroissant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCroissantKeyTyped(evt);
            }
        });

        jtxtCorompoloni.setBackground(new java.awt.Color(197, 167, 135));
        jtxtCorompoloni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCorompoloni.setText("0");
        jtxtCorompoloni.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jtxtCorompoloni.setEnabled(false);
        jtxtCorompoloni.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtCorompoloni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCorompoloniKeyTyped(evt);
            }
        });

        jtxtCheseeCake.setBackground(new java.awt.Color(197, 167, 135));
        jtxtCheseeCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCheseeCake.setText("0");
        jtxtCheseeCake.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jtxtCheseeCake.setEnabled(false);
        jtxtCheseeCake.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtCheseeCake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCheseeCakeKeyTyped(evt);
            }
        });

        jtxtCherryPie.setBackground(new java.awt.Color(197, 167, 135));
        jtxtCherryPie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCherryPie.setText("0");
        jtxtCherryPie.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jtxtCherryPie.setEnabled(false);
        jtxtCherryPie.setMinimumSize(new java.awt.Dimension(72, 22));
        jtxtCherryPie.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtCherryPie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCherryPieKeyTyped(evt);
            }
        });

        jtxtCookies.setBackground(new java.awt.Color(197, 167, 135));
        jtxtCookies.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCookies.setText("0");
        jtxtCookies.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jtxtCookies.setEnabled(false);
        jtxtCookies.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtCookies.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCookiesKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Foods");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/cro2.png"))); // NOI18N

        jLabel13.setText("Rp25.000,-");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/Picsart_23-12-17_13-52-15-374.png"))); // NOI18N

        jLabel15.setText("Rp28.000,-");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/chese.png"))); // NOI18N

        jLabel17.setText("Rp40.000,-");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/cher.png"))); // NOI18N

        jLabel19.setText("Rp25.000,-");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/cookies.jpg"))); // NOI18N

        jLabel21.setText("Rp23.000,-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchkCookies)
                            .addComponent(jchkCorompoloni)
                            .addComponent(jchkCroissant)
                            .addComponent(jchkCheseeCake)
                            .addComponent(jchkCherryPie)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel19))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtCorompoloni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCroissant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCheseeCake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCherryPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCookies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(213, 213, 213))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jchkCherryPie, jchkCheseeCake, jchkCookies, jchkCorompoloni, jchkCroissant});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtCherryPie, jtxtCheseeCake, jtxtCookies, jtxtCorompoloni, jtxtCroissant});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jchkCroissant)
                            .addComponent(jtxtCroissant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addComponent(jLabel12))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jchkCorompoloni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jtxtCorompoloni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jchkCheseeCake)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17))
                            .addComponent(jLabel16))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jchkCherryPie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)))
                        .addGap(7, 7, 7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jtxtCheseeCake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jtxtCherryPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jchkCookies))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtCookies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(100, 100, 100))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jchkCherryPie, jchkCheseeCake, jchkCookies, jchkCorompoloni, jchkCroissant});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtxtCherryPie, jtxtCheseeCake, jtxtCookies, jtxtCorompoloni, jtxtCroissant});

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, 310, 580));

        jPanel3.setBackground(new java.awt.Color(205, 183, 158));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(111, 78, 55)));
        jPanel3.setForeground(new java.awt.Color(111, 78, 55));

        jchkCoklatPanas.setText("Hot Chocolate");
        jchkCoklatPanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkCoklatPanasActionPerformed(evt);
            }
        });

        jchkGreenTea.setText("Green Tea");
        jchkGreenTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkGreenTeaActionPerformed(evt);
            }
        });

        jchkCoffee.setText("Coffee");
        jchkCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkCoffeeActionPerformed(evt);
            }
        });

        jchkMilkshake.setText("Milkshake");
        jchkMilkshake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMilkshakeActionPerformed(evt);
            }
        });

        jchkMineralWater.setText("Mineral Water");
        jchkMineralWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMineralWaterActionPerformed(evt);
            }
        });

        jtxtCoklatPanas.setBackground(new java.awt.Color(197, 167, 135));
        jtxtCoklatPanas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoklatPanas.setText("0");
        jtxtCoklatPanas.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jtxtCoklatPanas.setEnabled(false);
        jtxtCoklatPanas.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtCoklatPanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCoklatPanasActionPerformed(evt);
            }
        });
        jtxtCoklatPanas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCoklatPanasKeyTyped(evt);
            }
        });

        jtxtGreenTea.setBackground(new java.awt.Color(197, 167, 135));
        jtxtGreenTea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtGreenTea.setText("0");
        jtxtGreenTea.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jtxtGreenTea.setEnabled(false);
        jtxtGreenTea.setMinimumSize(new java.awt.Dimension(72, 22));
        jtxtGreenTea.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtGreenTea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtGreenTeaKeyTyped(evt);
            }
        });

        jtxtCoffee.setBackground(new java.awt.Color(197, 167, 135));
        jtxtCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoffee.setText("0");
        jtxtCoffee.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jtxtCoffee.setEnabled(false);
        jtxtCoffee.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtCoffee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCoffeeKeyTyped(evt);
            }
        });

        jtxtMilkshake.setBackground(new java.awt.Color(197, 167, 135));
        jtxtMilkshake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMilkshake.setText("0");
        jtxtMilkshake.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jtxtMilkshake.setEnabled(false);
        jtxtMilkshake.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtMilkshake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMilkshakeKeyTyped(evt);
            }
        });

        jtxtMineralWater.setBackground(new java.awt.Color(197, 167, 135));
        jtxtMineralWater.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMineralWater.setText("0");
        jtxtMineralWater.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jtxtMineralWater.setEnabled(false);
        jtxtMineralWater.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtMineralWater.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMineralWaterKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Drinks");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/cokl.png"))); // NOI18N

        jLabel22.setText("Rp28.000,-");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/green.png"))); // NOI18N

        jLabel25.setText("Rp28.000,-");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/kopi.png"))); // NOI18N

        jLabel27.setText("Rp22.000,-");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/straw.png"))); // NOI18N

        jLabel28.setText("Rp28.000,-");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication9/rsz_mineral_water.png"))); // NOI18N

        jLabel31.setText("Rp8.000,-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel29)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchkCoklatPanas)
                            .addComponent(jchkCoffee)
                            .addComponent(jchkMilkshake)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel22)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jchkMineralWater)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel31)))
                                .addComponent(jchkGreenTea)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(jLabel25))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtCoklatPanas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtGreenTea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCoffee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtMilkshake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtMineralWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtCoffee, jtxtCoklatPanas, jtxtGreenTea, jtxtMilkshake, jtxtMineralWater});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jchkCoklatPanas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel24)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jchkGreenTea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)
                                .addGap(54, 54, 54))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jtxtCoklatPanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtGreenTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jchkCoffee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jchkMilkshake)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jtxtMilkshake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jchkMineralWater)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jtxtMineralWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGap(38, 38, 38))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtxtCoffee, jtxtCoklatPanas, jtxtGreenTea, jtxtMilkshake, jtxtMineralWater});

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 124, 320, 580));

        jPanel4.setBackground(new java.awt.Color(205, 183, 158));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(111, 78, 55)));
        jPanel4.setForeground(new java.awt.Color(111, 78, 55));

        jLabel1.setText("Payment Method");

        jcmbpaymethod.setBackground(new java.awt.Color(197, 167, 135));
        jcmbpaymethod.setForeground(new java.awt.Color(111, 78, 55));
        jcmbpaymethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit Card", "QRIS" }));
        jcmbpaymethod.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jcmbpaymethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbpaymethodActionPerformed(evt);
            }
        });

        jtxtPay.setBackground(new java.awt.Color(197, 167, 135));
        jtxtPay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPay.setText("0");
        jtxtPay.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jtxtPay.setPreferredSize(new java.awt.Dimension(72, 22));

        jLabel2.setText("Pay");

        jtxtChange.setBackground(new java.awt.Color(197, 167, 135));
        jtxtChange.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jtxtChange.setPreferredSize(new java.awt.Dimension(72, 22));

        jtxtTax.setBackground(new java.awt.Color(197, 167, 135));
        jtxtTax.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jtxtTax.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });

        jtxtSubTotal.setBackground(new java.awt.Color(197, 167, 135));
        jtxtSubTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jtxtSubTotal.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });

        jtxtTotal.setBackground(new java.awt.Color(197, 167, 135));
        jtxtTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jtxtTotal.setPreferredSize(new java.awt.Dimension(72, 22));
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });

        jLabel3.setText("Change");

        jLabel4.setText("Tax");

        jLabel5.setText("Subtotal");

        jLabel6.setText("Total");

        jbuttonTotal.setBackground(new java.awt.Color(197, 167, 135));
        jbuttonTotal.setText("Total");
        jbuttonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonTotalActionPerformed(evt);
            }
        });

        jbuttonReset.setBackground(new java.awt.Color(197, 167, 135));
        jbuttonReset.setText("Reset");
        jbuttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonResetActionPerformed(evt);
            }
        });

        jtxtArea.setBackground(new java.awt.Color(197, 167, 135));
        jtxtArea.setColumns(20);
        jtxtArea.setRows(5);
        jtxtArea.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(111, 78, 55)));
        jScrollPane1.setViewportView(jtxtArea);

        jbuttonOrder.setBackground(new java.awt.Color(197, 167, 135));
        jbuttonOrder.setText("Order");
        jbuttonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonOrderActionPerformed(evt);
            }
        });

        jLabel7.setText("Data Pemesanan");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Payment");

        jbuttonExit.setBackground(new java.awt.Color(197, 167, 135));
        jbuttonExit.setText("Exit");
        jbuttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonExitActionPerformed(evt);
            }
        });

        jbuttonChange.setBackground(new java.awt.Color(197, 167, 135));
        jbuttonChange.setText("Change");
        jbuttonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonChangeActionPerformed(evt);
            }
        });

        jbuttonCetakPesanan.setBackground(new java.awt.Color(197, 167, 135));
        jbuttonCetakPesanan.setText("Cetak Pesanan");
        jbuttonCetakPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonCetakPesananActionPerformed(evt);
            }
        });

        jbuttonNewOrder.setBackground(new java.awt.Color(197, 167, 135));
        jbuttonNewOrder.setText("New Order");
        jbuttonNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonNewOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1)
                            .addComponent(jcmbpaymethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbuttonReset)
                            .addComponent(jbuttonTotal))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jbuttonChange))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbuttonCetakPesanan)
                                    .addComponent(jLabel3)
                                    .addComponent(jtxtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jbuttonOrder)
                            .addGap(18, 18, 18)
                            .addComponent(jbuttonNewOrder)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbuttonExit))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbuttonTotal)
                        .addGap(16, 16, 16)
                        .addComponent(jbuttonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbpaymethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonChange)
                    .addComponent(jbuttonCetakPesanan))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonOrder)
                    .addComponent(jbuttonExit)
                    .addComponent(jbuttonNewOrder))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 124, -1, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //Checkbox Onion Ring
    private void jchkCookiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkCookiesActionPerformed
        // TODO add your handling code here:
        if (jchkCookies.isSelected()){
            jtxtCookies.setEnabled(true);
            jtxtCookies.requestFocus();
            jtxtCookies.setText("");
        }
        else{
            jtxtCookies.setEnabled(false);
            jtxtCookies.setText("0");
        }    
    }//GEN-LAST:event_jchkCookiesActionPerformed

private JFrame frame;
    private void jbuttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonExitActionPerformed
        // TODO add your handling code here:
        // Kembali ke halaman login
        Login lg = new Login();
        lg.show();
        dispose();
        /*frame = new JFrame ("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Do you want to exit?", "425 Bakery", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }*/
    }//GEN-LAST:event_jbuttonExitActionPerformed

    private void jbuttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonResetActionPerformed
        // TODO add your handling code here:
        // textfield tiap menu bernilai 0 ketika klik reset button
        jtxtCroissant.setText("0");
        jtxtCorompoloni.setText("0");
        jtxtCheseeCake.setText("0");
        jtxtCherryPie.setText("0");
        jtxtCookies.setText("0");
        jtxtCoklatPanas.setText("0");
        jtxtGreenTea.setText("0");
        jtxtCoffee.setText("0");
        jtxtMilkshake.setText("0");
        jtxtMineralWater.setText("0");
        jtxtPay.setText("0");
        
        // textfield tiap menu disable
        jtxtCroissant.setEnabled(false);
        jtxtCorompoloni.setEnabled(false);
        jtxtCheseeCake.setEnabled(false);
        jtxtCherryPie.setEnabled(false);
        jtxtCookies.setEnabled(false);
        jtxtCoklatPanas.setEnabled(false);
        jtxtGreenTea.setEnabled(false);
        jtxtCoffee.setEnabled(false);
        jtxtMilkshake.setEnabled(false);
        jtxtMineralWater.setEnabled(false);
        
        // textfield di payment has no value
        jtxtTotal.setText(null);
        jtxtSubTotal.setText(null);
        jtxtTax.setText(null);
        jtxtChange.setText(null);
        
        //================================================
        
        // checkbox tiap menu unchecklist
        jchkCroissant.setSelected(false);
        jchkCorompoloni.setSelected(false);
        jchkCheseeCake.setSelected(false);
        jchkCherryPie.setSelected(false);
        jchkCookies.setSelected(false);
        jchkCoklatPanas.setSelected(false);
        jchkGreenTea.setSelected(false);
        jchkCoffee.setSelected(false);
        jchkMilkshake.setSelected(false);
        jchkMineralWater.setSelected(false);
        
    }//GEN-LAST:event_jbuttonResetActionPerformed

    private void jchkCroissantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkCroissantActionPerformed
        // TODO add your handling code here:
        if (jchkCroissant.isSelected()){ // jika checkbox suatu menu dichecklist maka
            jtxtCroissant.setEnabled(true); // textfield menu tersebut enable
            jtxtCroissant.requestFocus(); // cursor auto focus ke textfield tsb
            jtxtCroissant.setText(""); // textfield berisi kosong
        }
        else{ // jika tidak dichecklist
            jtxtCroissant.setEnabled(false); // textfield disable
            jtxtCroissant.setText("0"); // textfield bernilai 0
        }      
    }//GEN-LAST:event_jchkCroissantActionPerformed

    private void jtxtCroissantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCroissantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCroissantActionPerformed

    //Textfield hanya bisa diisi oleh angka
    private void jtxtCroissantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCroissantKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar(); // variabel iNumber: semua char dlm keyboard
        
        if (!(Character.isDigit(iNumber)) // jika character bukan digit maka
        ||(iNumber ==KeyEvent.VK_BACK_SPACE) // constant for the back_space virtual key
        ||(iNumber ==KeyEvent.VK_DELETE)){ // constant for the delete key
        evt.consume();
    }           
    }//GEN-LAST:event_jtxtCroissantKeyTyped

    private void jtxtCorompoloniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCorompoloniKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtCorompoloniKeyTyped
    }
    
    private void jtxtCheseeCakeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCheseeCakeKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtCheseeCakeKeyTyped
    }
    
    private void jtxtCherryPieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCherryPieKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtCherryPieKeyTyped
    }
    
    private void jtxtCookiesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCookiesKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtCookiesKeyTyped
    }
        
    private void jtxtCoklatPanasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCoklatPanasKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtCoklatPanasKeyTyped
    }
    
    private void jtxtGreenTeaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtGreenTeaKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtGreenTeaKeyTyped
    }
    
    private void jtxtCoffeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCoffeeKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtCoffeeKeyTyped
    }
    
    private void jtxtMilkshakeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMilkshakeKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtMilkshakeKeyTyped
    }
    
    private void jtxtMineralWaterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMineralWaterKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
        ||(iNumber ==KeyEvent.VK_BACK_SPACE)
        ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }//GEN-LAST:event_jtxtMineralWaterKeyTyped
    }
    
    private void jchkCorompoloniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkCorompoloniActionPerformed
        // TODO add your handling code here:
        if (jchkCorompoloni.isSelected()){
            jtxtCorompoloni.setEnabled(true);
            jtxtCorompoloni.requestFocus();
            jtxtCorompoloni.setText("");
        }
        else{
            jtxtCorompoloni.setEnabled(false);
            jtxtCorompoloni.setText("0");
        }    
    }//GEN-LAST:event_jchkCorompoloniActionPerformed

    private void jchkCheseeCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkCheseeCakeActionPerformed
        // TODO add your handling code here:
        if (jchkCheseeCake.isSelected()){
            jtxtCheseeCake.setEnabled(true);
            jtxtCheseeCake.requestFocus();
            jtxtCheseeCake.setText("");
        }
        else{
            jtxtCheseeCake.setEnabled(false);
            jtxtCheseeCake.setText("0");
        }    
    }//GEN-LAST:event_jchkCheseeCakeActionPerformed

    private void jchkCherryPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkCherryPieActionPerformed
        // TODO add your handling code here:
        if (jchkCherryPie.isSelected()){
            jtxtCherryPie.setEnabled(true);
            jtxtCherryPie.requestFocus();
            jtxtCherryPie.setText("");
        }
        else{
            jtxtCherryPie.setEnabled(false);
            jtxtCherryPie.setText("0");
        }    
    }//GEN-LAST:event_jchkCherryPieActionPerformed

    private void jchkCoklatPanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkCoklatPanasActionPerformed
        // TODO add your handling code here:
        if (jchkCoklatPanas.isSelected()){
            jtxtCoklatPanas.setEnabled(true);
            jtxtCoklatPanas.requestFocus();
            jtxtCoklatPanas.setText("");
        }
        else{
            jtxtCoklatPanas.setEnabled(false);
            jtxtCoklatPanas.setText("0");
        }    
    }//GEN-LAST:event_jchkCoklatPanasActionPerformed

    private void jchkGreenTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkGreenTeaActionPerformed
        // TODO add your handling code here:
        if (jchkGreenTea.isSelected()){
            jtxtGreenTea.setEnabled(true);
            jtxtGreenTea.requestFocus();
            jtxtGreenTea.setText("");
        }
        else{
            jtxtGreenTea.setEnabled(false);
            jtxtGreenTea.setText("0");
        }    
    }//GEN-LAST:event_jchkGreenTeaActionPerformed

    private void jchkCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkCoffeeActionPerformed
        // TODO add your handling code here:
        if (jchkCoffee.isSelected()){
            jtxtCoffee.setEnabled(true);
            jtxtCoffee.requestFocus();
            jtxtCoffee.setText("");
        }
        else{
            jtxtCoffee.setEnabled(false);
            jtxtCoffee.setText("0");
        }    
    }//GEN-LAST:event_jchkCoffeeActionPerformed

    private void jchkMilkshakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMilkshakeActionPerformed
        // TODO add your handling code here:
        if (jchkMilkshake.isSelected()){
            jtxtMilkshake.setEnabled(true);
            jtxtMilkshake.requestFocus();
            jtxtMilkshake.setText("");
        }
        else{
            jtxtMilkshake.setEnabled(false);
            jtxtMilkshake.setText("0");
        }    
    }//GEN-LAST:event_jchkMilkshakeActionPerformed

    private void jchkMineralWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMineralWaterActionPerformed
        // TODO add your handling code here:
        if (jchkMineralWater.isSelected()){
            jtxtMineralWater.setEnabled(true);
            jtxtMineralWater.requestFocus();
            jtxtMineralWater.setText("");
        }
        else{
            jtxtMineralWater.setEnabled(false);
            jtxtMineralWater.setText("0");
        }    
    }//GEN-LAST:event_jchkMineralWaterActionPerformed
   
    private void jbuttonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonTotalActionPerformed
        // TODO add your handling code here:
        // nilai pada textfield dimasukan pada tiap2 array
        itemcost[0] = Integer.parseInt(jtxtCroissant.getText());
        itemcost[1] = Integer.parseInt(jtxtCorompoloni.getText());
        itemcost[2] = Integer.parseInt(jtxtCheseeCake.getText());
        itemcost[3] = Integer.parseInt(jtxtCherryPie.getText());
        itemcost[4] = Integer.parseInt(jtxtCookies.getText());
        itemcost[5] = Integer.parseInt(jtxtCoklatPanas.getText());
        itemcost[6] = Integer.parseInt(jtxtGreenTea.getText());
        itemcost[7] = Integer.parseInt(jtxtCoffee.getText());
        itemcost[8] = Integer.parseInt(jtxtMilkshake.getText());
        itemcost[9] = Integer.parseInt(jtxtMineralWater.getText());
        
        // menghitung sub total
        iSubTotal = Price_Croissant*itemcost [0] + Price_Corompoloni*itemcost [1] 
                + Price_CheseeCake*itemcost [2] + Price_CherryPie*itemcost [3] 
                + Price_Cookies*itemcost [4] + Price_CoklatPanas*itemcost [5] + Price_GreenTea*itemcost [6] 
                + Price_Coffee*itemcost [7] + Price_Milkshake*itemcost [8] 
                + Price_MineralWater*itemcost [9] ;
        
        // menghitung pajak
        iTax = (iSubTotal*10)/100;
        
        // menghitung total keseluruhan
        iTotal = iSubTotal + iTax; 
            
            // mengoutputkan nilai tiap-tiap perhitungan pada masing2 textfield
            String cTax = String.format("Rp%d", iTax);
            jtxtTax.setText(cTax);
        
            String cSubTotal = String.format("Rp%d", iSubTotal);
            jtxtSubTotal.setText(cSubTotal);
        
            String cTotal = String.format("Rp%d", iTotal);
            jtxtTotal.setText(cTotal);
    }//GEN-LAST:event_jbuttonTotalActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed
    
    private void jbuttonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonChangeActionPerformed
        // TODO add your handling code here:
        // variabel iPay berisi nilai pada textfield pay
        iPay = Integer.parseInt(jtxtPay.getText()); 
        // variabel string berisi item yang kita pilih
        String PaymentMethod = (String)jcmbpaymethod.getSelectedItem();
        
        if (PaymentMethod == "Cash"){// jika memilih cash maka
            if (iPay >= iTotal){ // dan jika nilai iPay >= iTotal maka
                // mengoutputkan iPay - iTotal pada textfield change
                String cChange = String.format("Rp%d", iPay - iTotal);
                jtxtChange.setText(cChange);
            } // jika nilai iPay kurang maka
            else {
                // menampilkan message dialog "not enough cash"
                JOptionPane.showMessageDialog(null, "Not enough cash entered", 
                        "425 Bakery", JOptionPane.OK_OPTION);
            }
        }
        
        //jika memilih lainnya (debit card and qris) maka
        else {
            // hanya mengoutputkan iPay - iTotal pada textfield change
            String cChange = String.format("Rp%d", iPay - iTotal);
            jtxtChange.setText(cChange);
        }
    }//GEN-LAST:event_jbuttonChangeActionPerformed
    
    private void jbuttonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonOrderActionPerformed
        // TODO add your handling code here:
        String PaymentMethod = (String)jcmbpaymethod.getSelectedItem();
        
        //jika kita klik tombol order dan memilih cash, maka pesan yg ditampilkan
        if (PaymentMethod == "Cash"){
            JOptionPane.showMessageDialog(null, "Terima kasih Atas Pesanan Anda"+ "\n"
                    +"Pesanan Anda Akan Kami Proses");
        }
        
        //jika kita klik tombol order dan memilih debit card, maka pesan yg ditampilkan
        else if (PaymentMethod == "Debit Card"){
            JOptionPane.showMessageDialog(null, "Enter your debit card, please");
            JOptionPane.showMessageDialog(null, "Terima kasih Atas Pesanan Anda"+"\n"
                    +"Pesanan Anda Akan Kami Proses");
        }
        
        //jika kita klik tombol order dan memilih qris, maka pesan yg ditampilkan
        else {
            JOptionPane.showMessageDialog(null, "Scan the barcode, please");
            JOptionPane.showMessageDialog(null, "Terima kasih Atas Pesanan Anda"+"\n"
                    +"Pesanan Anda Akan Kami Proses");
        }
        
    }//GEN-LAST:event_jbuttonOrderActionPerformed
    
    private void jbuttonCetakPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonCetakPesananActionPerformed
        // TODO add your handling code here:
        String foods, drinks;
        
        //Foods
        StringBuffer var = new StringBuffer ();
        if (jchkCroissant.isSelected()) { // jika checkbox dichecklist, maka
            // menambahkan text pada checkbox dan nilai pada textfield ke dalam var
            var.append("\n");
            var.append(jchkCroissant.getText());
            var.append("\t");
            var.append(jtxtCroissant.getText());
        }  
        if (jchkCorompoloni.isSelected()) {
            var.append("\n");
            var.append(jchkCorompoloni.getText());
            var.append("\t");
            var.append(jtxtCorompoloni.getText());
        }  
        if (jchkCheseeCake.isSelected()) {
            var.append("\n");
            var.append(jchkCheseeCake.getText());
            var.append("\t");
            var.append(jtxtCheseeCake.getText());
        }  
        if (jchkCherryPie.isSelected()) {
            var.append("\n");
            var.append(jchkCherryPie.getText());
            var.append("\t");
            var.append(jtxtCherryPie.getText());
        }  
        if (jchkCookies.isSelected()) {
            var.append("\n");
            var.append(jchkCookies.getText());
            var.append("\t");
            var.append(jtxtCookies.getText());
        }
        // lalu program di atas disimpan pada variabel baru utk memudahkan pemanggilan
        foods = var.toString();
        
        //Drinks
        StringBuffer dri = new StringBuffer ();
        if (jchkCoklatPanas.isSelected()) {
            dri.append("\n");
            dri.append(jchkCoklatPanas.getText());
            dri.append("\t");
            dri.append(jtxtCoklatPanas.getText());
        }  
        if (jchkGreenTea.isSelected()) {
            dri.append("\n");
            dri.append(jchkGreenTea.getText());
            dri.append("\t");
            dri.append(jtxtGreenTea.getText());
        }  
        if (jchkCoffee.isSelected()) {
            dri.append("\n");
            dri.append(jchkCoffee.getText());
            dri.append("\t");
            dri.append(jtxtCoffee.getText());
        }  
        if (jchkMilkshake.isSelected()) {
            dri.append("\n");
            dri.append(jchkMilkshake.getText());
            dri.append("\t");
            dri.append(jtxtMilkshake.getText());
        }  
        if (jchkMineralWater.isSelected()) {
            dri.append("\n");
            dri.append(jchkMineralWater.getText());
            dri.append("\t");
            dri.append(jtxtMineralWater.getText());
        }  
        drinks = dri.toString();
        
        // mengoutputkan pada textarea
        jtxtArea.setText(
        "Foods\t: " +foods+ "\n"+
        "\nDrinks\t: " +drinks+ "\n"+
        "\nSub Total\t: "+jtxtSubTotal.getText()+"\n"+
        "Tax\t: "+jtxtTax.getText()+"\n"+
        "Total\t: "+jtxtTotal.getText()+"\n"+
        "Pay\t: Rp"+jtxtPay.getText()+"\n"+
        "Change\t: "+jtxtChange.getText()+"\n");
    }//GEN-LAST:event_jbuttonCetakPesananActionPerformed

    private void jtxtCoklatPanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCoklatPanasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCoklatPanasActionPerformed

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed
    
    // button new order -mike
    private void jbuttonNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonNewOrderActionPerformed
        // TODO add your handling code here:
        jtxtCroissant.setText("0");
        jtxtCorompoloni.setText("0");
        jtxtCheseeCake.setText("0");
        jtxtCherryPie.setText("0");
        jtxtCookies.setText("0");
        jtxtCoklatPanas.setText("0");
        jtxtGreenTea.setText("0");
        jtxtCoffee.setText("0");
        jtxtMilkshake.setText("0");
        jtxtMineralWater.setText("0");
        jtxtPay.setText("0");
        
        jtxtCroissant.setEnabled(false);
        jtxtCorompoloni.setEnabled(false);
        jtxtCheseeCake.setEnabled(false);
        jtxtCherryPie.setEnabled(false);
        jtxtCookies.setEnabled(false);
        jtxtCoklatPanas.setEnabled(false);
        jtxtGreenTea.setEnabled(false);
        jtxtCoffee.setEnabled(false);
        jtxtMilkshake.setEnabled(false);
        jtxtMineralWater.setEnabled(false);
        
        jtxtTotal.setText(null);
        jtxtSubTotal.setText(null);
        jtxtTax.setText(null);
        jtxtChange.setText(null);
        
        jtxtArea.setText("");//mengosongkan text area
        
        //================================================
        
        jchkCroissant.setSelected(false);
        jchkCorompoloni.setSelected(false);
        jchkCheseeCake.setSelected(false);
        jchkCherryPie.setSelected(false);
        jchkCookies.setSelected(false);
        jchkCoklatPanas.setSelected(false);
        jchkGreenTea.setSelected(false);
        jchkCoffee.setSelected(false);
        jchkMilkshake.setSelected(false);
        jchkMineralWater.setSelected(false);
    }//GEN-LAST:event_jbuttonNewOrderActionPerformed

    private void jcmbpaymethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbpaymethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbpaymethodActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    // run MainMenu
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbuttonCetakPesanan;
    private javax.swing.JButton jbuttonChange;
    private javax.swing.JButton jbuttonExit;
    private javax.swing.JButton jbuttonNewOrder;
    private javax.swing.JButton jbuttonOrder;
    private javax.swing.JButton jbuttonReset;
    private javax.swing.JButton jbuttonTotal;
    private javax.swing.JCheckBox jchkCherryPie;
    private javax.swing.JCheckBox jchkCheseeCake;
    private javax.swing.JCheckBox jchkCoffee;
    private javax.swing.JCheckBox jchkCoklatPanas;
    private javax.swing.JCheckBox jchkCookies;
    private javax.swing.JCheckBox jchkCorompoloni;
    private javax.swing.JCheckBox jchkCroissant;
    private javax.swing.JCheckBox jchkGreenTea;
    private javax.swing.JCheckBox jchkMilkshake;
    private javax.swing.JCheckBox jchkMineralWater;
    private javax.swing.JComboBox<String> jcmbpaymethod;
    private javax.swing.JTextArea jtxtArea;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtCherryPie;
    private javax.swing.JTextField jtxtCheseeCake;
    private javax.swing.JTextField jtxtCoffee;
    private javax.swing.JTextField jtxtCoklatPanas;
    private javax.swing.JTextField jtxtCookies;
    private javax.swing.JTextField jtxtCorompoloni;
    private javax.swing.JTextField jtxtCroissant;
    private javax.swing.JTextField jtxtGreenTea;
    private javax.swing.JTextField jtxtMilkshake;
    private javax.swing.JTextField jtxtMineralWater;
    private javax.swing.JTextField jtxtPay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
